### ISSUE TITLE
carriage return

### ISSUE THREAD

**Issue by mentaluproar** [pkmnct/homebridge-television-universal-control#3]
How do we insert a carriage return in UART commands?

**Comment by pkmnct** [comment]
You can use `\n`, but you must edit the command directly in the config file (or the UI config editor) rather than in the plugin settings under Homebridge Config UI X, since the UI does not display the carriage return (and seems to strip it out if editing).

**Comment by pkmnct** [comment]
It does look like I told you the wrong escaped character for a carriage return, my device expects a `\r` rather than a `\n`.
