### ISSUE TITLE
The home kit app does not show this accessory.

### ISSUE THREAD

**Issue by LucaSilva-r** [pkmnct/homebridge-television-universal-control#5]
I don't know what I am doing wrong, but the homekit app only shows one accessory and not this one. Could it be caused by the plugin configuration?

**Comment by pkmnct** [comment]
The plugin creates a  platform accessory, which means you must manually search for and add the television once it is configured. See the [Homebridge wiki for adding TVs](https://github.com/homebridge/homebridge/wiki/Connecting-Homebridge-To-HomeKit#how-to-add-homebridge-cameras--tvs) for more information.

You should see something like the following in your Homebridge log if you have configured the plugin correctly:
```
[11/9/2020, 4:12:41 PM] Please add [YOUR DEVICE NAME] manually in Home app. Setup Code: 123-45-678
```

If you don't see that, attach your configuration and I'll take a look.
